2025-08-14 10:51:41 [INFO    ] utils.images: Logger configurado. Arquivo de log: logs/catalog_20250814_105141.log
2025-08-14 10:51:41 [INFO    ] catalog_builder: Logger configurado. Arquivo de log: logs/catalog_20250814_105141.log
2025-08-14 10:51:41 [INFO    ] __main__: Logger configurado. Arquivo de log: logs/catalog_20250814_105141.log
2025-08-14 10:51:41 [INFO    ] __main__: Iniciando geração do catálogo com layout default
2025-08-14 10:51:41 [INFO    ] catalog_builder: Iniciando geração do catálogo...
2025-08-14 10:51:41 [ERROR   ] __main__: Erro fatal ao gerar catálogo: Excel file format cannot be determined, you must specify an engine manually.
Traceback (most recent call last):
  File "c:\Users\gustavo\Documents\Automation project\src\main.py", line 66, in main
    build_catalog(args, layout_config)
  File "c:\Users\gustavo\Documents\Automation project\src\catalog_builder.py", line 133, in build_catalog
    df, c_sku, c_nome, c_cat, c_img = load_product_data(args.excel)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gustavo\Documents\Automation project\src\utils\excel.py", line 17, in load_product_data
    df = pd.read_excel(path)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 1554, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
