2025-08-20 09:27:20 [INFO    ] src.utils.excel: Logger configurado. Arquivo de log: logs/catalog_20250820_092720.log
2025-08-20 09:27:20 [INFO    ] src.utils.images: Logger configurado. Arquivo de log: logs/catalog_20250820_092720.log
2025-08-20 09:27:20 [INFO    ] __main__: Logger configurado. Arquivo de log: logs/catalog_20250820_092720.log
2025-08-20 09:27:20 [INFO    ] __main__: Iniciando geração do catálogo em PDF...
2025-08-20 09:27:20 [INFO    ] src.utils.excel: Carregando planilha: data/produtos.xlsx
2025-08-20 09:27:21 [INFO    ] src.utils.excel: 575 produtos após remover valores nulos
2025-08-20 09:27:21 [INFO    ] __main__: Planilha de produtos carregada com 575 itens.
2025-08-20 09:27:21 [INFO    ] src.utils.excel: Carregando planilha de imagens: data/imagens/base_imagens.xlsx
2025-08-20 09:27:21 [ERROR   ] src.utils.excel: Arquivo de links de imagem não encontrado: data/imagens/base_imagens.xlsx
2025-08-20 09:27:21 [ERROR   ] __main__: Erro fatal ao gerar catálogo: [Errno 2] No such file or directory: 'data/imagens/base_imagens.xlsx'
Traceback (most recent call last):
  File "C:\Users\gustavo\Documents\Automation project\Catalogue-Automation\src\main.py", line 55, in main
    img_links_df = load_image_links(args.img_excel)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\Documents\Automation project\Catalogue-Automation\src\utils\excel.py", line 84, in load_image_links
    df = pd.read_excel(file_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\excel\_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\gustavo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\io\common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/imagens/base_imagens.xlsx'
